version: 2.1
jobs:

  build:
    docker:
      - image: circleci/node:12.19
      
    working_directory: ~/node-port-scanner
      
    steps:
      - checkout
      - run: npm install
      - run: npm fund
      - run: npm run usage